### PR TITLE
Add test to support old Java format

### PR DESCRIPTION
**Pull request by pawlos**
For now the test for old java format (radare2/#15152). Fix is on its way.

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
eta on the fix? This test should be marked as "broken" until it is fixed.

**Comment by pawlos** [comment]
@thestr4ng3r ETA - should be today. I have the fix just need to see if could be a bit simpler. Sorry for the test not being correctly marked didn't fully grasp those test statuses yet.

**Comment by thestr4ng3r** [comment]
No problem at all, it's @radare's fault if he merges unfixed tests.

**Comment by pawlos** [comment]
@thestr4ng3r ok. actually I can see I've made a typo in the test so I'll issue a fix soon. Could you point me how those tests statuses are stored? What should I push apart from the test to indicate its status?

**Comment by thestr4ng3r** [comment]
I've set the broken status in #1994 so that is fine for now. This is afaik the only real "status" that can be defined.
The r2r tool can help you write and edit tests too. For example (if broken is not set), if you run `r2r -i` after making changes in r2, it will ask you what to do with a failing test and you can tell it to set it as broken with `b` or make the current output the expected one with `f`:
Bildschirmfoto vom 2019-10-20 15-07-21

**Comment by pawlos** [comment]
@thestr4ng3r big thx! I'll try to be more careful next time with that.

**Pull request merged**
